image: node:latest

cache:
  paths:
    - node_modules/

test:
  script:
    - yarn install
    - yarn build

pages:
  variables:
    VUE_PUBLIC_PATH: "/cred-cat/credential-catalogue-ckan"
  script:
    - yarn install
    # We can't build directly into /public, so we first need
    # to build, then move.
    - yarn build
    - rm -rf public
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - fixing-pages
