version: '3.7'
services:
  credcat:
    build:
      context: .
      dockerfile: Dockerfile.prod
    networks:
      - proxy
    labels:
      traefik.enable: "true"
      traefik.http.routers.credcat-insecure.rule: Host(`credcat.ssi-lab.nl`)
      traefik.http.routers.credcat-insecure.middlewares: redirectToHttps@file,securityHeaders@file
      traefik.http.routers.credcat.tls.certresolver: letsencrypt
      traefik.http.routers.credcat.tls.options: safeTLSOptions@file
      traefik.http.routers.credcat.middlewares: securityHeaders@file
      traefik.http.routers.credcat.rule: Host(`credcat.ssi-lab.nl`)

networks:
  proxy:
    external: true
